# Generated by Django 4.2.11 on 2026-04-23 00:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('juros', 'Apenas Juros'), ('capital_parcial', 'Capital Parcial + Juros'), ('capital_total', 'Quitação Total (Capital + Juros)'), ('parcela', 'Parcela Parcelada')], max_length=20)),
                ('data_pagamento', models.DateField(db_index=True)),
                ('valor_juros_pagos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('valor_capital_pago', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('capital_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_depois', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='loans.emprestimo')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_parcela', to='loans.parcelaemprestimo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento', '-created_at'],
                'indexes': [models.Index(fields=['emprestimo', 'data_pagamento'], name='payments_pa_emprest_c66fce_idx')],
            },
        ),
    ]
