# Generated by Django 4.2.11 on 2026-04-23 01:06

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalOperacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_capital', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Soma de todo o capital disponível para empréstimos.', max_digits=14, verbose_name='Capital Total do Operador')),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capital Operacional',
                'verbose_name_plural': 'Capital Operacional',
            },
        ),
    ]
