# Generated by Django 4.2.11 on 2026-06-05 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_add_capital_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitaloperacional',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
