# Generated by Django 4.2.11 on 2026-06-05 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_emprestimo_data_ultimo_acumulo_and_more'),
        ('core', '0002_capitaloperacional_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoCapital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('aporte', 'Aporte (entrada de crédito)'), ('retirada', 'Retirada'), ('emprestimo', 'Empréstimo concedido'), ('recebimento', 'Recebimento')], db_index=True, max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField(db_index=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_capital', to='loans.emprestimo')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Capital',
                'verbose_name_plural': 'Movimentações de Capital',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
