# Generated by Django 4.2.11 on 2026-04-23 00:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('veiculo', 'Veículo (Carro/Moto)'), ('imovel', 'Imóvel'), ('eletronico', 'Eletrônico'), ('joia', 'Joia / Relógio'), ('outro', 'Outro')], max_length=15)),
                ('descricao', models.TextField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual_recuperacao', models.DecimalField(decimal_places=4, default=Decimal('0.7000'), help_text='Ex: 0.7000 = 70% de recuperação estimada', max_digits=5)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='loans.emprestimo')),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
            },
        ),
        migrations.CreateModel(
            name='DocumentoGarantia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('arquivo', models.FileField(upload_to='garantias/documentos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='collaterals.garantia')),
            ],
            options={
                'verbose_name': 'Documento da Garantia',
                'verbose_name_plural': 'Documentos das Garantias',
            },
        ),
    ]
