# Generated by Django 4.2.11 on 2026-04-23 00:28

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True, validators=[core.validators.validate_cpf])),
                ('rg', models.CharField(blank=True, max_length=30, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes/fotos/')),
                ('telefone_principal', models.CharField(max_length=20)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('redes_sociais', models.JSONField(blank=True, default=dict)),
                ('origem', models.CharField(choices=[('indicacao', 'Indicação'), ('proprio', 'Prospecção Própria'), ('redes_sociais', 'Redes Sociais'), ('outro', 'Outro')], default='proprio', max_length=20)),
                ('perfil_psicologico', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('classificacao', models.CharField(choices=[('verde', '🟢 Bom Pagador'), ('amarelo', '🟡 Regular'), ('vermelho', '🔴 Mau Pagador')], db_index=True, default='verde', max_length=10)),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_renda', 'Comprovante de Renda'), ('comprovante_residencia', 'Comprovante de Residência'), ('contrato', 'Contrato Assinado'), ('outro', 'Outro')], max_length=30)),
                ('arquivo', models.FileField(upload_to='clientes/documentos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos dos Clientes',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['classificacao', 'deleted_at'], name='customers_c_classif_1d96c8_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cidade', 'estado'], name='customers_c_cidade_460d57_idx'),
        ),
    ]
