# Generated by Django 4.2.11 on 2026-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_residencia',
            field=models.CharField(blank=True, choices=[('propria', 'Própria'), ('alugada', 'Alugada'), ('familiar', 'Casa de Familiar'), ('financiada', 'Financiada'), ('outros', 'Outros')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='origem',
            field=models.CharField(choices=[('indicacao', 'Indicação'), ('proprio', 'Prospecção Própria'), ('redes_sociais', 'Redes Sociais'), ('boato', 'Boato / Divulgação Informal'), ('outro', 'Outro')], default='proprio', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cnh', 'CNH'), ('cpf', 'CPF'), ('comprovante_renda', 'Comprovante de Renda'), ('comprovante_residencia', 'Comprovante de Residência'), ('contrato', 'Contrato Assinado'), ('outro', 'Outro')], max_length=30),
        ),
    ]
