# Generated by Django 4.2.11 on 2026-06-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_cliente_prioridade_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='renda_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Usada para calcular o comprometimento de renda.', max_digits=12, null=True, verbose_name='Renda mensal (R$)'),
        ),
    ]
