# Generated by Django 4.2.11 on 2026-06-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_cliente_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=40)),
                ('cor', models.CharField(choices=[('slate', 'Cinza'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('red', 'Vermelho'), ('purple', 'Roxo')], default='slate', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag de Cliente',
                'verbose_name_plural': 'Tags de Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='customers.tagcliente'),
        ),
    ]
