# Generated by Django 4.2.11 on 2026-06-07 22:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_tagcliente_cliente_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, validators=[core.validators.validate_cpf]),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'cpf'), name='uniq_cpf_por_owner_ativo'),
        ),
    ]
