# Generated by Django 4.2.11 on 2026-04-23 00:28

import core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('comum', 'Comum (Sem Parcela Fixa)'), ('parcelado', 'Parcelado'), ('diaria', 'Diária')], db_index=True, max_length=15)),
                ('subtipo_parcelado', models.CharField(blank=True, choices=[('fixo', 'Parcela Fixa (Juros sobre Capital Inicial)'), ('sac', 'Parcela Decrescente — SAC')], max_length=10, null=True)),
                ('capital_inicial', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.validate_capital_positivo])),
                ('capital_atual', models.DecimalField(decimal_places=2, help_text='Saldo devedor atual. Atualizado a cada pagamento.', max_digits=12)),
                ('taxa_juros_mensal', models.DecimalField(decimal_places=6, help_text='Ex: 0.050000 = 5,00% ao mês', max_digits=8, validators=[core.validators.validate_taxa_juros])),
                ('n_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, help_text='Data de vencimento final (última parcela ou vencimento avençado).', null=True)),
                ('data_quitacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('quitado', 'Quitado'), ('inadimplente', 'Inadimplente'), ('cancelado', 'Cancelado'), ('renegociado', 'Renegociado')], db_index=True, default='ativo', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='customers.cliente')),
                ('emprestimo_origem', models.ForeignKey(blank=True, help_text='Preenchido quando este empréstimo é uma renegociação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renegociacoes', to='loans.emprestimo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_juros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_devedor_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_devedor_depois', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('parcialmente_pago', 'Parcialmente Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='loans.emprestimo')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['emprestimo', 'numero'],
                'unique_together': {('emprestimo', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['cliente', 'status'], name='loans_empre_cliente_e2911d_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['status', 'data_vencimento'], name='loans_empre_status_a10764_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['tipo', 'status'], name='loans_empre_tipo_e69bd1_idx'),
        ),
    ]
