# Generated by Django 4.2.11 on 2026-06-05 02:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_backfill_venc_comum'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_ultimo_acumulo',
            field=models.DateField(blank=True, help_text='Data do último ciclo de juros lançado em juros_acumulados. Controla o acúmulo idempotente feito pelo cron.', null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='juros_acumulados',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Juros já lançados e ainda em aberto (empréstimo comum). NÃO rende juros — sem capitalização (juros sobre juros).', max_digits=12),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
